export interface MedicineCatalogItem {
  name: string;
  purpose: string;
}

const MEDICINE_CATALOG: MedicineCatalogItem[] = [
  { name: 'Paracetamol', purpose: 'Pain and fever relief' },
  { name: 'Ibuprofen', purpose: 'Pain, swelling, and fever relief' },
  { name: 'Diclofenac', purpose: 'Pain and inflammation relief' },
  { name: 'Naproxen', purpose: 'Long-lasting pain and inflammation relief' },
  { name: 'Aceclofenac', purpose: 'Joint and muscle pain relief' },
  { name: 'Tramadol', purpose: 'Moderate to severe pain relief' },
  { name: 'Mefenamic Acid', purpose: 'Menstrual and general pain relief' },
  { name: 'Acetaminophen', purpose: 'Pain and fever relief' },
  { name: 'Cetirizine', purpose: 'Allergy symptom relief' },
  { name: 'Levocetirizine', purpose: 'Allergy and sneezing control' },
  { name: 'Loratadine', purpose: 'Non-drowsy allergy relief' },
  { name: 'Fexofenadine', purpose: 'Non-drowsy allergy symptom relief' },
  { name: 'Desloratadine', purpose: 'Allergy and itching relief' },
  { name: 'Hydroxyzine', purpose: 'Allergy, itching, and anxiety support' },
  { name: 'Chlorpheniramine', purpose: 'Cold and allergy symptom relief' },
  { name: 'Montelukast', purpose: 'Allergy and asthma support' },
  { name: 'Bilastine', purpose: 'Allergy and urticaria symptom relief' },
  { name: 'Rupatadine', purpose: 'Allergy and hives symptom control' },
  { name: 'Omeprazole', purpose: 'Acidity and reflux reduction' },
  { name: 'Pantoprazole', purpose: 'Acid reflux and gastric protection' },
  { name: 'Esomeprazole', purpose: 'Acid reflux and ulcer protection' },
  { name: 'Lansoprazole', purpose: 'Acid reflux and gastritis treatment' },
  { name: 'Rabeprazole', purpose: 'Acidity and reflux symptom control' },
  { name: 'Ranitidine', purpose: 'Acid control and heartburn relief' },
  { name: 'Famotidine', purpose: 'Acid and heartburn control' },
  { name: 'Sucralfate', purpose: 'Ulcer lining protection' },
  { name: 'Domperidone', purpose: 'Nausea and gastric motility support' },
  { name: 'Ondansetron', purpose: 'Nausea and vomiting control' },
  { name: 'Oral Rehydration Salts', purpose: 'Dehydration and loose motion support' },
  { name: 'Loperamide', purpose: 'Loose motion control' },
  { name: 'Metformin', purpose: 'Blood sugar control in diabetes' },
  { name: 'Glimepiride', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Gliclazide', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Sitagliptin', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Vildagliptin', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Teneligliptin', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Empagliflozin', purpose: 'Type 2 diabetes and heart-kidney support' },
  { name: 'Dapagliflozin', purpose: 'Type 2 diabetes blood sugar control' },
  { name: 'Insulin Glargine', purpose: 'Long-acting insulin for diabetes' },
  { name: 'Insulin Aspart', purpose: 'Rapid-acting insulin for diabetes' },
  { name: 'Amlodipine', purpose: 'Blood pressure control' },
  { name: 'Telmisartan', purpose: 'High blood pressure management' },
  { name: 'Losartan', purpose: 'Blood pressure control and kidney protection' },
  { name: 'Olmesartan', purpose: 'Blood pressure control' },
  { name: 'Valsartan', purpose: 'Blood pressure and heart failure support' },
  { name: 'Ramipril', purpose: 'Blood pressure and heart protection' },
  { name: 'Enalapril', purpose: 'Blood pressure and heart support' },
  { name: 'Atenolol', purpose: 'Blood pressure and heart rate control' },
  { name: 'Metoprolol', purpose: 'Blood pressure and heart rhythm control' },
  { name: 'Bisoprolol', purpose: 'Blood pressure and heart support' },
  { name: 'Hydrochlorothiazide', purpose: 'Blood pressure control and fluid reduction' },
  { name: 'Furosemide', purpose: 'Fluid overload and blood pressure support' },
  { name: 'Atorvastatin', purpose: 'Cholesterol lowering' },
  { name: 'Rosuvastatin', purpose: 'Cholesterol and cardiovascular risk reduction' },
  { name: 'Simvastatin', purpose: 'Cholesterol lowering' },
  { name: 'Fenofibrate', purpose: 'Triglyceride reduction' },
  { name: 'Aspirin', purpose: 'Blood thinning and pain relief' },
  { name: 'Clopidogrel', purpose: 'Blood clot prevention' },
  { name: 'Warfarin', purpose: 'Blood clot prevention and stroke risk reduction' },
  { name: 'Apixaban', purpose: 'Blood clot and stroke prevention' },
  { name: 'Rivaroxaban', purpose: 'Blood clot prevention' },
  { name: 'Azithromycin', purpose: 'Bacterial infection treatment' },
  { name: 'Amoxicillin', purpose: 'Bacterial infection treatment' },
  { name: 'Amoxicillin Clavulanate', purpose: 'Broad-spectrum bacterial infection treatment' },
  { name: 'Doxycycline', purpose: 'Bacterial and skin infection treatment' },
  { name: 'Cefixime', purpose: 'Bacterial infection treatment' },
  { name: 'Cefuroxime', purpose: 'Bacterial infection treatment' },
  { name: 'Cefpodoxime', purpose: 'Bacterial infection treatment' },
  { name: 'Levofloxacin', purpose: 'Respiratory and urinary infection treatment' },
  { name: 'Ofloxacin', purpose: 'Bacterial infection treatment' },
  { name: 'Ciprofloxacin', purpose: 'Urinary and bacterial infection treatment' },
  { name: 'Metronidazole', purpose: 'Anaerobic and gut infection treatment' },
  { name: 'Tinidazole', purpose: 'Parasitic and anaerobic infection treatment' },
  { name: 'Fluconazole', purpose: 'Fungal infection treatment' },
  { name: 'Clotrimazole', purpose: 'Topical fungal infection treatment' },
  { name: 'Acyclovir', purpose: 'Viral infection treatment support' },
  { name: 'Oseltamivir', purpose: 'Influenza antiviral treatment' },
  { name: 'Albendazole', purpose: 'Deworming treatment' },
  { name: 'Vitamin D3', purpose: 'Vitamin D supplementation' },
  { name: 'Vitamin B12', purpose: 'Nerve and blood health support' },
  { name: 'Iron Folic Acid', purpose: 'Iron deficiency and anemia support' },
  { name: 'Calcium Carbonate', purpose: 'Bone health supplementation' },
  { name: 'Calcium Citrate', purpose: 'Bone health supplementation' },
  { name: 'Multivitamin', purpose: 'General nutritional support' },
  { name: 'Folic Acid', purpose: 'Anemia and pregnancy support' },
  { name: 'Zinc Sulfate', purpose: 'Immunity and recovery support' },
  { name: 'Vitamin C', purpose: 'Immunity and antioxidant support' },
  { name: 'Magnesium', purpose: 'Muscle and nerve support' },
  { name: 'Probiotic', purpose: 'Gut flora and digestion support' },
  { name: 'Levothyroxine', purpose: 'Thyroid hormone replacement' },
  { name: 'Liothyronine', purpose: 'Thyroid hormone supplementation' },
  { name: 'Prednisolone', purpose: 'Inflammation and allergy control' },
  { name: 'Deflazacort', purpose: 'Inflammation and autoimmune symptom control' },
  { name: 'Salbutamol', purpose: 'Asthma and breathing relief' },
  { name: 'Budesonide', purpose: 'Airway inflammation control' },
  { name: 'Formoterol', purpose: 'Long-acting bronchodilation support' },
  { name: 'Tiotropium', purpose: 'Long-acting airway opening support' },
  { name: 'Fluticasone', purpose: 'Nasal and airway inflammation control' },
  { name: 'Mupirocin', purpose: 'Topical bacterial skin infection treatment' },
  { name: 'Permethrin', purpose: 'Scabies and lice treatment' },
];

export function getMedicineSuggestions(query: string, limit = 6): MedicineCatalogItem[] {
  const normalized = query.trim().toLowerCase();
  if (normalized.length < 3) {
    return [];
  }

  return MEDICINE_CATALOG.filter((item) => item.name.toLowerCase().includes(normalized)).slice(0, limit);
}

export function getMedicinePurposeByName(name: string): string | undefined {
  const normalized = name.trim().toLowerCase();
  const found = MEDICINE_CATALOG.find((item) => item.name.toLowerCase() === normalized);
  return found?.purpose;
}
